// src/constants/notificationEvents.js
// Business event constants for the notification system

module.exports = {
  // Account Management Events
  ACCOUNT_APPROVAL_REQUEST: 'ACCOUNT_APPROVAL_REQUEST',
  ACCOUNT_APPROVED: 'ACCOUNT_APPROVED',
  ACCOUNT_REJECTED: 'ACCOUNT_REJECTED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',

  // KYC Events
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_RE_SUBMITTED: 'KYC_RE_SUBMITTED',

  // Withdrawal Events
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_PROCESSED: 'WITHDRAWAL_PROCESSED',

  // Chat/Communication Events
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  CHAT_UNREAD_COUNT: 'CHAT_UNREAD_COUNT',
  CHAT_TYPING: 'CHAT_TYPING',
  CHAT_DELIVERED: 'CHAT_DELIVERED',
  CHAT_READ: 'CHAT_READ',

  // Payment Events
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',

  // System Events
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
  SYSTEM_UPDATE: 'SYSTEM_UPDATE',
  FEATURE_ANNOUNCEMENT: 'FEATURE_ANNOUNCEMENT'
};